//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_Worck_Server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabTrackerDB : DbContext
    {
        public LabTrackerDB()
            : base("name=LabTrackerDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Cource> Cources { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<ListLab> ListLabs { get; set; }
        public virtual DbSet<ListLabTeacher> ListLabTeachers { get; set; }
        public virtual DbSet<ListStudent> ListStudents { get; set; }
        public virtual DbSet<ListTeacher> ListTeachers { get; set; }
        public virtual DbSet<Semestr> Semestrs { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<SubGroup> SubGroups { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<WeekDay> WeekDays { get; set; }
        public virtual DbSet<PlansPass> PlansPasses { get; set; }
        public virtual DbSet<StudentPass> StudentPasses { get; set; }
    }
}
