//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_Worck_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListLab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListLab()
        {
            this.ListLabTeachers = new HashSet<ListLabTeacher>();
            this.PlansPasses = new HashSet<PlansPass>();
            this.StudentPasses = new HashSet<StudentPass>();
        }
    
        public int IDLab { get; set; }
        public string NameLab { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> IDCource { get; set; }
        public string IDSpeciality { get; set; }
        public Nullable<int> IDSem { get; set; }
    
        public virtual Cource Cource { get; set; }
        public virtual Semestr Semestr { get; set; }
        public virtual Speciality Speciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListLabTeacher> ListLabTeachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlansPass> PlansPasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPass> StudentPasses { get; set; }
    }
}
