//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_Worck_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlansPass
    {
        public int IDPlan { get; set; }
        public Nullable<int> IDGroup { get; set; }
        public Nullable<int> IDLab { get; set; }
        public string Date { get; set; }
        public int Quantity { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ListLab ListLab { get; set; }
    }
}
